---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
      ansible_host: 192.168.1.50
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/jenkins_vm_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
